### ISSUE TITLE
生成轨迹后，move_to_element_with_offset函数结果执行结果有问题

### ISSUE THREAD

**Issue by Jie-OY** [iYgnohZ/crack_geetest#2]
在生成(x,y,t)列表后，执行函数action.move_to_element_with_offset(to_element=slide, xoffset=22 + x, yoffset=y + 22).perform()，发现滑块总是超出验证框。

于是，我对每执行一次的结果截图，然后放在MSpaint里放大看发现：例如列表是这样的：
1 -1 0.2     3 -1 0.5      2 0 0.3      3 1 0.3     1 1 0.3

它第一次xoffet 1 ，第二次不是3，而是 1 + 3 =4；第三次不是2， 而是 1 +3 +2 =6.也就是说，它移动的不是x，而是x加上其前面所有项之和，不知道是什么原因？

换函数 move_by_offset也是这样。

selenium = 2.53.6 3.0都用过，结果一样
python = 3.5
Chrome = 55（用的是最新的chrome驱动）

**Comment by haijunt** [comment]
可以用python2.7 及selenium的对应版本，做个测试，可能真的是版本问题。
还有，确定一点是滑块总是超出验证框？
我的滑块轨迹产生原理如下：
1，超出或者留出一个随机值的距离。
2，随机产生距离段
3， 每次产生 1 px , 进行补充。
我后面还会再检查一下，会有及时补充。

**Comment by Jie-OY** [comment]
我试过您的算法和自己想的写的算法，结果都是那样。其实，关键的点在于，它第n次移动的像素点**恰好**是算法生成的前n次应该移动的像素点之和，这绝非而然。但是，我查了很久，没有找到原因。未知的某个bug?不知道，已经弃坑了 - - 您可以随时关闭这个issue了
